Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,6 +49,24 @@ jobs:
           fi
           echo "Appium server is ready."
 
+      - name: Boot Simulator
+        run: |
+          # Find the UDID of the iPhone SE (3rd generation) for iOS 18.1
+          UDID=$(xcrun simctl list devices 'iPhone SE (3rd generation)' | grep '(18.1)' | head -n 1 | awk -F'[()]' '{print $2}')
+          
+          echo "Booting simulator with UDID: $UDID"
+          
+          # Exit if the simulator wasn't found
+          if [ -z "$UDID" ]; then
+            echo "Could not find a simulator matching the criteria."
+            exit 1
+          fi
+          
+          # Boot the specific simulator and wait for it to be ready
+          xcrun simctl bootstatus "$UDID" -b
+          
+          echo "Simulator booted successfully."
+
       - name: DEBUG
         run: xcrun simctl list devices booted
           
